# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PCRasterSlope
                                 A QGIS plugin
 PCRaster Slope
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-24
        copyright            : (C) 2020 by Hans van der Kwast (IHE Delft)
        email                : h.vanderkwast@un-ihe.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Hans van der Kwast (IHE Delft)'
__date__ = '2020-10-24'
__copyright__ = '(C) 2020 by Hans van der Kwast (IHE Delft)'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PCRasterSlope class from file PCRasterSlope.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pcraster_slope import PCRasterSlopePlugin
    return PCRasterSlopePlugin()
